#数据库
HOSTNAME = '127.0.0.1'
PORT     = '3306'
DATABASE = 'forumPro'
USERNAME = 'root'
PASSWORD = '1234'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}'.format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = "dahai2222"

#邮箱配置
MAIL_SERVER = "smtp.qq.com"
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME= "553876245@qq.com"
MAIL_PASSWORD = "zcrcumjbvflpbdej"
MAIL_DEFAULT_SENDER="553876245@qq.com"